// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;

public class JavafindTestV2
{
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "/usr/local/bin/chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void JavaFindTest() {
    // Test name: java find
    // Step # | name | target | value
    // 1 | open | https://docs.oracle.com/javase/9/docs/api/overview-summary.html | 
    driver.get("https://docs.oracle.com/javase/9/docs/api/overview-summary.html");
    // 2 | setWindowSize | 865x958 | 
    driver.manage().window().setSize(new Dimension(865, 958));
    // 3 | type | id=search | java.lang.S
    driver.findElement(By.id("search")).sendKeys("java.lang.S");
    // 4 | mouseOver | linkText=java.lang.System.LoggerFinder | 
    {
      WebElement element = driver.findElement(By.linkText("java.lang.System.LoggerFinder"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 5 | mouseOver | linkText=java.lang.StackOverflowError | 
    {
      WebElement element = driver.findElement(By.linkText("java.lang.StackOverflowError"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 6 | mouseOver | linkText=java.lang.StringIndexOutOfBoundsException | 
    {
      WebElement element = driver.findElement(By.linkText("java.lang.StringIndexOutOfBoundsException"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 7 | mouseOver | linkText=java.lang.StringBuilder | 
    {
      WebElement element = driver.findElement(By.linkText("java.lang.StringBuilder"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 8 | mouseOut | linkText=java.lang.StringBuilder | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 9 | click | linkText=java.lang.String | 
    driver.findElement(By.linkText("java.lang.String")).click();
    // 10 | click | css=.rowColor:nth-child(3) > .colConstructorName a | 
    driver.findElement(By.cssSelector(".rowColor:nth-child(3) > .colConstructorName a")).click();
    // 11 | click | id=search | 
    driver.findElement(By.id("search")).click();
    // 12 | type | id=search | javax.swing.jfram
    driver.findElement(By.id("search")).sendKeys("javax.swing.jfram");
    // 13 | mouseOver | linkText=javax.swing.JFrame.AccessibleJFrame | 
    {
      WebElement element = driver.findElement(By.linkText("javax.swing.JFrame.AccessibleJFrame"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 14 | mouseOut | linkText=javax.swing.JFrame.AccessibleJFrame | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 15 | click | linkText=javax.swing.JFrame | 
    driver.findElement(By.linkText("javax.swing.JFrame")).click();
    // 16 | click | css=.altColor:nth-child(4) > .colConstructorName .memberNameLink > a | 
    driver.findElement(By.cssSelector(".altColor:nth-child(4) > .colConstructorName .memberNameLink > a")).click();
  }
}
