// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;
public class JavafindTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void javafind() {
    driver.get("https://docs.oracle.com/javase/9/docs/api/overview-summary.html");
    driver.manage().window().setSize(new Dimension(865, 958));
    driver.findElement(By.id("search")).sendKeys("java.lang.S");
    {
      WebElement element = driver.findElement(By.linkText("java.lang.System.LoggerFinder"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.linkText("java.lang.StackOverflowError"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.linkText("java.lang.StringIndexOutOfBoundsException"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.linkText("java.lang.StringBuilder"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("java.lang.String")).click();
    driver.findElement(By.cssSelector(".rowColor:nth-child(3) > .colConstructorName a")).click();
    driver.findElement(By.id("search")).click();
    driver.findElement(By.id("search")).sendKeys("javax.swing.jfram");
    driver.findElement(By.id("search")).sendKeys(Keys.DOWN);
    driver.findElement(By.id("search")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".altColor:nth-child(4) > .colConstructorName .memberNameLink > a")).click();
  }
}
